language: php

php:
  - 5.6

branches:
  except:
    - gh-pages

before_script:
  - composer install -n --prefer-source
  - ./vendor/bin/codecept build
  - chmod -R 777 ./db

script:
  - ./vendor/bin/codecept run

notifications:
  slack: code-ninja-io:uSrXFfUaMNvRj3I8tQHWDH1j
